name: qr_code_reader
description: "Projeto de leitor de QRCode"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2
  riverpod: ^2.6.1
  provider: ^6.1.2
  go_router: ^14.8.0
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations
